### ISSUE TITLE
大佬未来可期啊

### ISSUE THREAD

**Issue by piapiapiapapapa** [XiaoRanLiu3119/TVBoxOS-Mobile#11]
加油加油加油！

**Comment by XiaoRanLiu3119** [comment]
嗨,啥大佬,落魄安卓开发发挥点余热。感谢感谢

**Comment by ZhiZhengWenHui** [comment]
这个多仓可以优化一下，这样看着比较好看，要是麻烦就算了，嘿嘿，加油哦！
![Uploading _0_wifi_0.jpg…]()
![Uploading _wifi_0.jpg…]()

**Comment by XiaoRanLiu3119** [comment]
> 这个多仓可以优化一下，这样看着比较好看，要是麻烦就算了，嘿嘿，加油哦！
> ![Uploading _0_wifi_0.jpg…]()
> ![Uploading _wifi_0.jpg…]()
> 
> 

咋图也挂了，是我这的原因吗

**Comment by XiaoRanLiu3119** [comment]
> 这个多仓可以优化一下，这样看着比较好看，要是麻烦就算了，嘿嘿，加油哦！
> ![Uploading _0_wifi_0.jpg…]()
> ![Uploading _wifi_0.jpg…]()
> 
> 

咋图也挂了，是我这的原因吗

**Comment by 1771245847** [comment]
大佬，能不能增加一个夜间模式，还有能否在设置那里加一个切换解码方式功能，[硬解码/软解码]，否则进入直播界面，默认软解码，最后一个小小的建议是那个软件名字昵称，MBox还是改为TVBox.名字不如以前看的舒服。谢谢

**Comment by XiaoRanLiu3119** [comment]
> 大佬，能不能增加一个夜间模式，还有能否在设置那里加一个切换解码方式功能，[硬解码/软解码]，否则进入直播界面，默认软解码，最后一个小小的建议是那个软件名字昵称，MBox还是改为TVBox.名字不如以前看的舒服。谢谢

解码给忘了下次加上。
想先适配安卓10以后的深色模式,快,但低版本用不着,其他方案工作量稍微大点,我合计下。
tvbox太多啦,手机版好歹要有个名字区分开,又想不到好名字,我在考虑征求大家意见

**Comment by 1771245847** [comment]
> > 大佬，能不能增加一个夜间模式，还有可以在设置那里加一个切换解码方式功能，[硬解码/软解码]，不然进入直播界面，默认软解码，最后一个空间建议是那个软件名字昵称，MBox还是改为TVBox。名字不如以前看的舒服。谢谢
> 
> 解码给忘了下加上。 想先改装安卓10以后的深度模式，快，但低版本用不着，其他方案工作量有点大点，我汇总下。tvbox太多啦， 手机版好要歹歹有一个名字区分开，又想不到好名字，我在考虑征求大家的意见

好的，收到

**Comment by piapiapiapapapa** [comment]
要加的还有很多，比如：
视频播放页的片头，片尾，播放器切换，软硬解，倍速，刷新，画面比例等，哈哈哈哈哈哈哈哈，不急，让大佬慢慢来，加油，奥利给！
