### ISSUE TITLE
大佬，多仓代码能往白猫盒推一下吗？

### ISSUE THREAD

**Issue by chengxue2020** [XiaoRanLiu3119/TVBoxOS-Mobile#14]
大佬好，能把订阅多仓、多线路的代码向上游白猫仓库推一下吗？自己改了几次不成功，谢谢

**Comment by XiaoRanLiu3119** [comment]
这周工作有点多。按多仓/多线路的字段取就好啦,看SubscriptionActivity
![image](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/62411322/00cd571f-8072-4878-a1a3-c6975f91a1d1)

**Comment by chengxue2020** [comment]
谢谢大佬，我再试试

**Comment by XiaoRanLiu3119** [comment]
不过白猫仓库是哪个喔

**Comment by c7877** [comment]
他的白猫应该说的是原版的，也就是俊版的…

**Comment by XiaoRanLiu3119** [comment]
> 他的白猫应该说的是原版的，也就是俊版的…

噢噢白猫和上游愣是没对上

**Comment by chengxue2020** [comment]
是的，俊版（ https://github.com/q215613905/TVBoxOS）。我个人比较菜，试了没成功，大佬能推一下多仓代码或者教一下怎么修改吗？
