### ISSUE TITLE
0.0.7在线升级到0.0.8后，进入订阅管理会报错

### ISSUE THREAD

**Issue by chen1234hao** [XiaoRanLiu3119/TVBoxOS-Mobile#15]
0.0.7在线升级到0.0.8后，进入订阅管理会报错，要求重启，重启后问题依然存在

**Comment by XiaoRanLiu3119** [comment]
> 0.0.7在线升级到0.0.8后，进入订阅管理会报错，要求重启，重启后问题依然存在

刚改了,麻烦卸载或清空app数据后安装0.1版本
