### ISSUE TITLE
Mbox牛皮，大佬辛苦

### ISSUE THREAD

**Issue by shenxian0809** [XiaoRanLiu3119/TVBoxOS-Mobile#17]
大佬这个版本真的是太牛皮了，真的是我用过最好的版本，提两天建议哈，一是加入DLNA投屏功能，二是加入手机重力感应上下180°转屏的功能或者是加入一个转屏的按钮也可以。另外问一下大佬有没有打赏渠道？希望能够提供一点绵薄之力

**Comment by shenxian0809** [comment]
@XiaoRanLiu3119 大佬可以考虑一下吗？

**Comment by XiaoRanLiu3119** [comment]
这俩摸鱼时都不好调,一直也没整
等我搁家开发研究研究投屏。我全屏相关代码改的太烂了,后续优化优化

**Comment by shenxian0809** [comment]
> 关代码改的太烂了,后续优

大佬已经很厉害了，感觉做的已经是相当成功了，可以考虑在github的项目里放一个打赏的二维码，为爱发电也要有点收益

**Comment by XiaoRanLiu3119** [comment]
感谢感谢，先不了，看大佬们的项目接触不少东西，当做学习了
