### ISSUE TITLE
小米平板全屏看视频底部小白条不会消失

### ISSUE THREAD

**Issue by grantting** [XiaoRanLiu3119/TVBoxOS-Mobile#19]
小米平板全屏看视频底部小白条不会消失

**Comment by XiaoRanLiu3119** [comment]
没平板，截图看看

**Comment by grantting** [comment]
> 没平板，截图看看

小米13上也出现
![Screenshot_2023-09-28-19-59-46-052_com github tvb](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/51224250/cf6b3f00-f2d9-4a7b-92cd-4e0fb8f1f037)

**Comment by XiaoRanLiu3119** [comment]
后续适配下

**Comment by grantting** [comment]
> 后续适配下

十分感谢，辛苦！
