### ISSUE TITLE
添加首页线路快捷刷新，播放时显示时间和进度 还有投屏，方便使用，谢谢。

### ISSUE THREAD

**Issue by jllyzjs** [XiaoRanLiu3119/TVBoxOS-Mobile#21]
添加首页线路快捷刷新，播放时显示时间和进度
还有投屏，方便使用，谢谢。

**Comment by XiaoRanLiu3119** [comment]
首页线路快捷刷新是什么？

**Comment by jllyzjs** [comment]
在首页清空首页数据源的缓存，其他版是长按，首页数据源的名字，还有长按首页的"主页"两字。

**Comment by XiaoRanLiu3119** [comment]
噢这个呀，后续得加，投屏等等看

**Comment by jllyzjs** [comment]
上次应该是我没说对，应该是在首页长按"主页"二字，重新获取订阅接口数据，不是清空接口缓存。这样订阅接口的新内容就不用重新启动APP了
