### ISSUE TITLE
剧集标题显示问题(见图一)

### ISSUE THREAD

**Issue by piapiapiapapapa** [XiaoRanLiu3119/TVBoxOS-Mobile#22]
由于设计的集数显示距离长度过短（一行3列），导致某些资源（尤其阿狸资源）或者集数标题过长的剧集，无法直观的看到集数。
建议可参考其他壳子的显示方法：
自动识别集数标题长度，以触发一行两列或者一行三列或者一行四列显示。
手机：红米K50
具体可看下图其他壳子的显示结果。
![IMG_20230929_101627.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/105154711/8c9e607e-61f8-4aac-9983-360761c66995)

![Screenshot_2023-09-29-10-05-15-358_com.fongmi.android.tv.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/105154711/14731f28-7f9a-403b-bc6f-84ca964ada8f)

![Screenshot_2023-09-29-10-02-32-418_com.movie.store.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/105154711/3f85d2f1-9434-43c4-830d-7274ff0a1d0e)

![Screenshot_2023-09-29-10-18-41-373_com.fongmi.android.tv.jpg](https://g![Screenshot_2023-09-29-10-22-13-013_com.movie.store.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/105154711/57640163-1477-4e74-80e7-d03982996fbd)

c25-4cab-b595-de486ab450fe)

![Screenshot_2023-09-29-10-22-13-013_com.movie.store.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/105154711/1ef2a0f8-5a2f-411b-a5be-d843d7e67647)

**Comment by XiaoRanLiu3119** [comment]
在计划中，节后的

**Comment by piapiapiapapapa** [comment]
太赞了，大佬中秋快乐

**Comment by XiaoRanLiu3119** [comment]
中秋快乐中秋快乐

**Comment by yunboxtvj** [comment]
大佬,搜索速度太慢了,增加搜索线程数。搜索ui布局,参考影视仓5.08，最好横屏显示。

影视仓4.0版,悬浮窗口很有用，5.0精简代码,悬浮窗口彻底删除了。

俊版增加了,荐片和磁力链播放，磁力链常用功能。

**Comment by yunboxtvj** [comment]
中秋快乐，搜索应该横屏显示，竖屏找站源太麻烦了。

**Comment by yunboxtvj** [comment]
![Screenshot_20230929_201309_com mygithub0 tvbox57_edit_621263521925514](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/541ad1ed-b68d-4991-ac78-88fc11a65a9e)

**Comment by yunboxtvj** [comment]
俊版和影视仓,剧集是1-40集折叠起来。
![Screenshot_20230929_230537_com mygithub0 tvbox57_edit_630711013153760](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/40940c5b-cc2b-4ba8-b2a5-488a7f2e07ed)

**Comment by XiaoRanLiu3119** [comment]
> 大佬,搜索速度太慢了,增加搜索线程数。搜索ui布局,参考影视仓5.08，最好横屏显示。
> 
> 影视仓4.0版,悬浮窗口很有用，5.0精简代码,悬浮窗口彻底删除了。
> 
> 俊版增加了,荐片和磁力链播放，磁力链常用功能。

搜索线程后续加。磁力我看下。

**Comment by piapiapiapapapa** [comment]
> 中秋快乐，搜索应该横屏显示，竖屏找站源太麻烦了。

这是手机版，不是tv版

**Comment by yunboxtvj** [comment]
https://github.com/dlgt7/Box20230917/commit/2ea0f7da2ad4613627ac47c1912ec95ff6b690b9

**Comment by XiaoRanLiu3119** [comment]
> [dlgt7/Box20230917@2ea0f7d](https://github.com/dlgt7/Box20230917/commit/2ea0f7da2ad4613627ac47c1912ec95ff6b690b9)

我fork时已支持支持荐片，不好使？

**Comment by yunboxtvj** [comment]
磁力链播放不出来，比如说黄金行动。

黄金行动,#genre#
黄金行动,magnet:?xt=urn:btih:087e5808544b550dde4f48f5a70960b5b3b6dfb1&dn=[www.mp4us.com]72小时-黄金行动.2023.HD1080p.国粤双语中字.mp4&tr=https://tracker.iriseden.fr:443/announce&tr=https://tr.highstar.shop:443/announce&tr=https://tr.fuckbitcoin.xyz:443/announce&tr=https://tr.doogh.club:443/announce&tr=https://tr.burnabyhighstar.com:443/announce&tr=https://t.btcland.xyz:443/announce&tr=http://vps02.net.orel.ru:80/announce&tr=https://tracker.kuroy.me:443/announce&tr=http://tr.cili001.com:8070/announce&tr=http://t.overflow.biz:6969/announce&tr=http://t.nyaatracker.com:80/announce&tr=http://open.acgnxtracker.com:80/announce&tr=http://nyaa.tracker.wf:7777/announce&tr=http://home.yxgz.vip:6969/announce&tr=http://buny.uk:6969/announce&tr=https://tracker.tamersunion.org:443/announce&tr=https://tracker.nanoha.org:443/announce&tr=https://tracker.loligirl.cn:443/announce&tr=udp://bubu.mapfactor.com:6969/announce&tr=http://share.camoe.cn:8080/announce&tr=udp://movies.zsw.ca:6969/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://tracker.sylphix.com:6969/announce&tr=http://95.216.22.207:9001/announce
黄金行动,ed2k://|file|【高清MP4电影www.mp4us.com】72xs-hjxd.2023.HD1080p.gysyzz.mp4|2305704007|b4c289f7e631d541ce5a9f0f6104e01c|/
东方不败之风云再起,https://vip.ffzy-play6.com/20221112/6204_738fdb50/2000k/hls/index.m3u8#https://vip.ffzy-play6.com/20221112/6203_105abf2a/2000k/hls/index.m3u8

**Comment by yunboxtvj** [comment]
http://shuyuan.miaogongzi.net/shuyuan/1696085818.txt

**Comment by XiaoRanLiu3119** [comment]
> 俊版和tak99可以播放 http://shuyuan.miaogongzi.net/shuyuan/1696085818.txt

俊佬有几次修复，等我抄抄的

**Comment by yunboxtvj** [comment]
tvbox配置规则,道长有个直播转本地js.另外jar包也有个直播转本地。
![Screenshot_20230930_115611](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/2725e1d3-277f-4591-9235-fd521a0af0b2)
![Screenshot_20230930_115317_com github tvbox osc taka_edit_653917609939802](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/6f832973-6f0f-4852-a8bb-ee3896db0ff4)

**Comment by yunboxtvj** [comment]
蜂蜜大佬的影视tv,支持道长js格式转py,而且支持猫影视js。
影视TV是开源，猫影视源也越来越多。

**Comment by yunboxtvj** [comment]
![Uploading QQ截图20230918190640.png…]()

**Comment by XiaoRanLiu3119** [comment]
> tvbox配置规则,道长大佬有个直播转点播js.另外jar包也有个直播转点播。
> 
> [zhixc/CatVodTVSpider@0347a43](https://github.com/zhixc/CatVodTVSpider/commit/0347a43d2edc3331642a788ca6e30990f3d003f1)
> 
> ![Screenshot_20230930_115611](https://user-images.githubusercontent.com/146441988/271754013-2725e1d3-277f-4591-9235-fd521a0af0b2.jpg) ![Screenshot_20230930_115317_com github tvbox osc taka_edit_653917609939802](https://user-images.githubusercontent.com/146441988/271754015-6f832973-6f0f-4852-a8bb-ee3896db0ff4.jpg)

直播转点播不好用的尝试切换播放器
![image](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/62411322/be053c6e-06f6-4ea4-b6ab-8edd47bd308d)

**Comment by XiaoRanLiu3119** [comment]
> TVBox道长源和猫影视源比较火,未来主力视频源。 道长py和猫影视js，早晚都要加上。

用影视不香么，又专业。目前精力有限，相对稳定之后研究

**Comment by yunboxtvj** [comment]
直播源格式太多,没有必要研究直播播放器。影视tv研究半年,一堆直播格式播放不了。

**Comment by XiaoRanLiu3119** [comment]
> 直播源格式太多,没有必要研究直播播放器。影视tv研究半年,一堆直播格式播放不了。
> 
> 影视仓直播稍微好一些,mitv和巴士tv已经支持。

窜行了兄弟，我是说直播转点播看不了的切换播放器试试。
而js格式转py没用过不懂，py和猫影视js的支持是后面研究

**Comment by yunboxtvj** [comment]
这个软件已经支持js转py,他也是抄道长的drpybox软件。
https://github.com/dlgt7/Box20230917

**Comment by yunboxtvj** [comment]
测试了新版，新版可以隐藏导航栏。运行比较流畅,这个版本比前几个稳定。

**Comment by yunboxtvj** [comment]
测试了新版，新版可以隐藏导航栏。播放器的解析速度很快,这个版本比前几个稳定。

主页加两个图标，直播图标和收藏图标。点击图标进入直播和收藏夹。

整一个追剧模式，片头片尾都设置90秒，播放器增加一个追剧按钮。

**Comment by yunboxtvj** [comment]
exo升级了隧道播放模式，专门用于播放4K片源。

**Comment by 96wangyang** [comment]
> 测试了新版，新版可以隐藏导航栏。播放器的解析速度很快,这个版本比前几个稳定。
> 
> 主页加两个图标，直播图标和收藏图标。点击图标进入直播和收藏夹。
> 
> 整一个追剧模式，片头片尾都设置90秒，播放器增加一个追剧按钮。

不要搞得那么多按钮，简单点挺好，也不要什么追剧模式，每部剧开头结尾时长都不一样，搞什么固定固定90s
