### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by grantting** [XiaoRanLiu3119/TVBoxOS-Mobile#23]
1. 播放界面里的选集图标能否改成文字“选集”，刚开始确实不知道这个按钮啥用，尝试后才知道有一定学习过程
2. 底部的按钮太集中，能否把设置放到右侧边，或者顶部时间栏一侧，变成侧边弹窗的形式
3. 长按倍速能否增加例如5x，8x等

**Comment by XiaoRanLiu3119** [comment]
好的,功能完善后着手优化

**Comment by piapiapiapapapa** [comment]
【一些小建议】
1.直播界面各个频道之间的间距可以拉开一点，目前有点太挤，稍不注意可能点错，可参考下图；
2.增加直播界面在中间位置可以上下滑动来切换频道（目前左边是调亮度，右边是调声音）。

**Comment by piapiapiapapapa** [comment]
![IMG_20231010_125641.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/105154711/517e2a1d-6917-4521-8790-e7c6a90971f4)

**Comment by XiaoRanLiu3119** [comment]
> ![IMG_20231010_125641.jpg](https://user-images.githubusercontent.com/105154711/273781544-517e2a1d-6917-4521-8790-e7c6a90971f4.jpg)

直播ui等等我看集中优化下

**Comment by yunboxtvj** [comment]
投屏和播放器设置，隔开一定距离。这两个按键容易按错，锁屏不应该放左边，左边摄像头会挡住锁屏。

**Comment by XiaoRanLiu3119** [comment]
> 投屏和播放器设置，隔开一定距离。这两个按键容易按错，锁屏不应该放左边，左边摄像头会挡住锁屏。

ok，这速度，我手机还没跑呢，还得是你，锁屏我留距离，右边转过来一样挡

**Comment by yunboxtvj** [comment]
锁屏和投屏,影视仓是放在右边中间.
![Uploading Screenshot_20231011_182553_com.mygithub0.tvbox57.jpg…]()

**Comment by yunboxtvj** [comment]
![Uploading Screenshot_20231011_182553_com.mygithub0.tvbox57.jpg…]()

**Comment by yunboxtvj** [comment]
搜索展示加个文字展示，另外听歌和小说，考虑熄屏播放。
