### ISSUE TITLE
小建议支持py和自定义直播

### ISSUE THREAD

**Issue by jllyzjs** [XiaoRanLiu3119/TVBoxOS-Mobile#24]
1最好能支持py接口配置http://101.34.67.237/config/2
2支持自定义链接电视台直播列表

**Comment by yunboxtvj** [comment]
支持py简单，关键要支持道长py，以及猫影视的js。taka99改版，已经支持爱老板js引擎了，这个引擎搜索速度是俊版四倍。

**Comment by XiaoRanLiu3119** [comment]
> 1最好能支持py接口配置http://101.34.67.237/config/2 2支持自定义链接电视台直播列表

自定义链接是说单独配置直播地址吧，会弄的

**Comment by yunboxtvj** [comment]
cat猫影视参考，猫影视加密文件都可以。
https://github.com/watson1982/drpy

**Comment by XiaoRanLiu3119** [comment]
> cat猫影视参考，猫影视加密文件都可以。 https://github.com/watson1982/drpy

不懂,先完善tvbox,不做额外的兼容,后面再说

**Comment by yunboxtvj** [comment]
taka99版tvbox,兼容了猫影视播放，另外换了爱老板引擎。

**Comment by XiaoRanLiu3119** [comment]
> taka99版tvbox,兼容了猫影视播放，另外换了爱老板quick js引擎。

技术时间优先,小门小户的,没大佬Contribute乱改不妥

**Comment by yunboxtvj** [comment]
原版taka99做对比,就知道修改哪里

**Comment by yunboxtvj** [comment]
播放器加一个竖屏播放，抖音很多视频是竖频

**Comment by yunboxtvj** [comment]
已经支持PY接口
