### ISSUE TITLE
非常好用，感谢大大！

### ISSUE THREAD

**Issue by 96wangyang** [XiaoRanLiu3119/TVBoxOS-Mobile#25]
首先感谢作者您的付出!

软件使用体验和ui都非常棒，目前版本用起来不错，使用上基本没问题。

提3点建议，您可以参考一下：
1.播放界面 ‘来源’ 那里优化一下，感觉布局不够和谐，然后再增加换源功能，其实就是搜索功能，因为有的源质量不好方便更换，如图其他壳子类似的换源功能，图1，图2。
2.设置界面增加一个主题颜色选项，可以自主选择暗色主题或跟随系统，图3。
3.主页内容增加一个关闭主页选项，有的源自带推荐页面，有时会与软件主页重复，图4。
谢谢您！
![IMG_20231011_121113](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/147572937/1fc360cd-7e66-4493-b53f-d032302518eb)
![IMG_20231011_121155](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/147572937/1fca00d3-55ab-49e0-a936-f4993d443790)
![IMG_20231011_120955](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/147572937/71f22b14-8cd0-452f-97cd-6588fee4bb4d)
![IMG_20231011_121032](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/147572937/923729d0-963a-4695-ad8f-2499757645ca)

**Comment by 96wangyang** [comment]
![IMG_20231011_120955](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/147572937/6509e0da-effd-4b60-8839-b0673fec3693)
![IMG_20231011_121032](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/147572937/fb4f1fcd-1a2f-4c6f-b6fa-fdcbe146001c)
![IMG_20231011_121113](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/147572937/c8524822-8e87-4cbb-ae83-05783fe1ed7d)
![IMG_20231011_121155](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/147572937/ba7da06e-1ab8-4e23-8952-f6d45654bb2e)

**Comment by yunboxtvj** [comment]
这么多功能，应该很难完成，功能越多bug越多。作者也很忙，除非有大佬加入。即使有大佬，修改bug也耗精力。

**Comment by XiaoRanLiu3119** [comment]
谢谢。这些也是我一直想改但没时间的,快捷换源最近会加上,自动换和其他的可能靠后些
