### ISSUE TITLE
taka99原版

### ISSUE THREAD

**Issue by yunboxtvj** [XiaoRanLiu3119/TVBoxOS-Mobile#27]
更新了cat影视，大佬可以去看看。俊版js引擎和taka99一样，直接引用修改。
https://github.com/takagen99/Box

**Comment by XiaoRanLiu3119** [comment]
看到俊版有pr了,上午我copy到本地,搜索体感没啥区别呢,有什么作用么,不太了解

**Comment by yunboxtvj** [comment]
他是js引擎解析速度快，俊版七七.js，进入首页要慢五秒。至于搜索速度，你线程加到100,速度自然飞起。

**Comment by yunboxtvj** [comment]
![Screenshot_20231013_135326](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/b0bd350b-bfdd-4e40-baf6-9fc7061cd193)

**Comment by yunboxtvj** [comment]
最关键的问题，搜索展示为文字。最好是横屏双行显示，搜索速度非常快。

**Comment by yunboxtvj** [comment]
![Screenshot_20231013_140844_com mygithub0 tvbox57_edit_69604845744586](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/509ae257-eb59-4115-a811-ad0dd228c5b1)
![Screenshot_20231013_135326](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/f50dcbf5-20a7-48c9-b2bd-9f73cbf092fd)

**Comment by XiaoRanLiu3119** [comment]
不行,我本地和tk的都试了,好多线路搜索崩溃或加载不出首页tab,现存这么多线路,如何升级

**Comment by yunboxtvj** [comment]
俊佬估计也会更新，估计taka99还是有些区别

**Comment by yunboxtvj** [comment]
这个源是引用高兄，至于升级在cat文件夹。
https://github.com/gaotianliuyun/gao

**Comment by XiaoRanLiu3119** [comment]
tk我跑完了,一样,饭太硬的首页tab出不来,道长js的剧集搜索高频崩溃,你测测看

**Comment by yunboxtvj** [comment]
这个代码是猫爪大佬写的，他自己改版的taka99是可以。

**Comment by yunboxtvj** [comment]
这个代码是猫爪大佬写的，他自己改版的taka99是可以。

**Comment by yunboxtvj** [comment]
编译出来猫影视可以进入首页，至于道长的话，估计是快搜代码问题

**Comment by yunboxtvj** [comment]
taka99原版编译出来，猫影视可以进入首页，至于道长js的话，估计是快搜代码问题。高频搜索问题，剧名模糊匹配。
饭太硬首页，不清楚哪个接口。jar包问题，首页出不来，xbpq新版有bug,我用旧版xbpq.

**Comment by XiaoRanLiu3119** [comment]
应该不止这些问题,我看fm的电报群最近也在吐槽qjs,虽然不懂,但看起来并不顺利

**Comment by yunboxtvj** [comment]
道长js没有问题，完全支持呀，老兄是用的哪个源。

**Comment by XiaoRanLiu3119** [comment]
三方收集里看到的,写的道长,不知是不是 https://pastebin.com/raw/5NHaxyGR

**Comment by yunboxtvj** [comment]
俊版升级也改了搜索代码，变成了模糊匹配，模糊匹配就会高频搜索。不是引擎问题，俊版之前是精准搜索。

**Comment by XiaoRanLiu3119** [comment]
直播只调ui。我只有jar来着，你说的猫影视是更新这个quickjs就支持的一些源么，和我理解的新版猫影视源是一个么，听说猫源有加密

**Comment by yunboxtvj** [comment]
猫爪大佬，早就解密了吧，猫影视和道长都是用的quick js。只不过俊版quick js，解析效率慢。

**Comment by yunboxtvj** [comment]
猫爪大佬，早就解密了吧，猫影视和道长都是用的quick js。只不过俊版quick js，解析效率慢。jar包执行效率比js高，搜索线程数改成100,js一样搜索很快。

**Comment by yunboxtvj** [comment]
更新就可以了，只是一些崩溃bug.

**Comment by yunboxtvj** [comment]
更新就可以了，只是一些崩溃bug,不清楚修复吗

**Comment by yunboxtvj** [comment]
更新就可以了，猫影视加密也可以。只是一些崩溃bug,不清楚修复吗

**Comment by XiaoRanLiu3119** [comment]
搜索我试好像问题不大，有些接口首页还是加载不出来

**Comment by yunboxtvj** [comment]
猫影视一些源本身就有问题，一些是嗅探代码，还有一部分网站换了域名。本身就是加密，没有办法改域名。
一般用道长js写源，十五分钟搞定一个站源。

**Comment by yunboxtvj** [comment]
猫影视一些源本身就有问题，一些是嗅探代码，还有一部分网站换了域名。本身就是加密，没有办法改域名。
一般用道长js写源，十五分钟搞定一个站源。道长站源，基本都能加载，更新速度快。

**Comment by yunboxtvj** [comment]
俊版有一个问题，js需要清理缓存，不然一些站源加载不出来，但是可以搜索出来。

**Comment by XiaoRanLiu3119** [comment]
这么吊，我也想尝试写写源，不过只会java和js，等搞个群加下你，再加些想交流的，电报属实用不习惯

**Comment by yunboxtvj** [comment]
道长js有模板，大概有十个模板。视频cms系统，基本上就这十套系统。往上面套就是，需要变的只是嗅探代码，道长嗅探代码，五种左右吧。

**Comment by yunboxtvj** [comment]
最简单方法，下载道长所有的源。看视频网站是哪种cms系统，搜索道长所有源，匹配出来就可以。

**Comment by yunboxtvj** [comment]
比如说最常见的md壳和st壳
var rule = {
    title:'电影先生',
    host:'https://dianyi.ng',
    // homeUrl:'/',
    url:'/pianku-fyclass--------fypage---.html',
    searchUrl:'https://dianyi.ng/search--------------.html?wd=**',
    searchable:2,//是否启用全局搜索,
    quickSearch:0,//是否启用快速搜索,
    filterable:0,//是否启用分类筛选,
    headers:{//网站的请求头,完整支持所有的,常带ua和cookies
        'User-Agent':'MOBILE_UA',
        // "Cookie": "searchneed=ok"
    },
    class_name:'电影&电视剧&动漫&综艺',
	class_url:'dianying&dianshiju&dongman&zongyi',
    
    play_parse:true,
    lazy:'',
    limit:6,
    推荐:'.module-items;.module-item&&.module-item-cover;img&&alt;img&&data-src;.module-item-text&&Text;a&&href',
    double:true, // 推荐内容是否双层定位
    一级:'.module-items;img&&alt;img&&data-src;.module-item-text&&Text;a&&href',
    二级:{"title":"h1&&Text;.video-info-main&&spann:eq(0)&&Text;.video-info-main&&span:eq(2)&&Text","img":".mobile-play&&img&&data-src","desc":".video-info-main&&span:eq(3)&&Text;.video-info-main&&span:eq(5)&&Text;.video-info-main&&span:eq(7)&&Text","content":".video-info-content&&Text","tabs":".module-tab-content&&span","lists":".sort-item:eq(#id) a"},
    搜索:'.module-items;h3&&Text;img&&data-src;a&&Text;a&&href',
}

**Comment by yunboxtvj** [comment]
看片狂人是fed壳，道长冷曦影视也是fed壳。
https://github.com/yunboxtvj/TVBoxDIY

**Comment by yunboxtvj** [comment]
看片狂人是fed壳，道长冷曦影视也是fed壳。一级和二级代码套用冷曦，只要改下发布页、分类、搜索、嗅探。十五分钟时间，完全够用了。二级没有必要写太详细，一级代码写对完事。简介、导演、年代、主演，浪费很多时间。当然二级代码，也是可以去写模板，我认为没有必要。道长、XYQhiker、海阔视界，大部分都是jsoup写法。XYQhiker更简单一些，比道长js快一些。
https://github.com/yunboxtvj/TVBoxDIY

**Comment by yunboxtvj** [comment]
用java写源，很多人xpath截取，正则也有人用。验证识别、宝塔防护、嗅探代码、ssl验证，没有现成代码抄，还要编译成jar包。XBPQ和道长js，这些内容都有解决方法。

**Comment by XiaoRanLiu3119** [comment]
谢谢，大概清楚啥意思了，有空再研究研究，熟悉了应该就很简单

**Comment by yunboxtvj** [comment]
推荐:可以不写
搜索和一级：数组、标题、图片、副标题、链接
tab_exclude:线路名排除
host发布页或者网址
hostJs:发布页请求头和截取网址链接数组
url:分类网址、searchUrl搜索网址、
class_name:分类名、class_url:分类替换词

lazy嗅探、title标题、img图片、tabs线路数组、lists播放数组、desc地区、年代、导演 主演、content剧情

**Comment by yunboxtvj** [comment]
推荐:可以不写
搜索和一级：数组、标题、图片、副标题、链接
tab_exclude:线路名排除
host发布页或者网址
hostJs:发布页请求头和截取网址链接数组
url:分类网址、searchUrl搜索网址、
class_name:分类名、class_url:分类替换词

lazy嗅探、title标题、img图片、tabs线路数组、lists播放数组、desc地区、年代、导演 主演、content剧情

比如说干饭影视，基本上就是首图st壳变种，stui替换成ewave完事。
https://github.com/yunboxtvj/TVBoxDIY

**Comment by XiaoRanLiu3119** [comment]
我才看明白道长的咋用的,简单来讲是不是源还是按CatVodSpider指定的json配置去写,内部就是"ext"指向你前面说的按规则写的js文件,api指向drpy.min.js包的路径,源中如果还有csp就也得指定spider

**Comment by XiaoRanLiu3119** [comment]
如果写源是不是只需按道长教程写js,而dypy.min.js工具包是固定的,最后形成json的源配置文件就可以了

**Comment by yunboxtvj** [comment]
可以本地文件
{"key":"海阔","name":"官┃海阔","type":3,"api":"csp_XYQHiker","ext":"clan://Download/简写.json"},
{"key":"drpy_js_脚本","name":"官 | 脚本","type":3,"api":"https://agit.ai/yu/gao/raw/branch/master/lib/drpy2.min.js","searchable":1,"quickSearch":1,"changeable":0,"ext":"clan://Download/简写.js"},

**Comment by yunboxtvj** [comment]
可以本地文件,道长lib文件夹下载到本地，调用本地drpy2.min.js
{"key":"海阔","name":"官┃海阔","type":3,"api":"csp_XYQHiker","ext":"clan://Download/简写.json"},
{"key":"drpy_js_脚本","name":"官 | 脚本","type":3,"api":"clan://lib/drpy2.min.js","searchable":1,"quickSearch":1,"changeable":0,"ext":"clan://Download/简写.js"},

**Comment by XiaoRanLiu3119** [comment]
真吊啊.一样壳发布的资源,jsoup就可以用一样的类查询,合着点点网站替换url和其他参数就完事了

**Comment by yunboxtvj** [comment]
道长还把js转化成py,各种tvbox源，思路都借鉴了道长，包括py一些源。

**Comment by yunboxtvj** [comment]
道长还把js转化成py,各种tvbox源。思路都借鉴了道长，包括py一些源，直接过验证码和宝塔。

**Comment by XiaoRanLiu3119** [comment]
得，越了解越刑了,常说的XYQhiker、海阔、道长，就类似于drpy.js里面的写法呗，drpy也是道长所创，而ext通通是为这些写法定好的拓展规则文件

**Comment by yunboxtvj** [comment]
XYQhiker可以前后缀截取，也可以jousp。网上有一些案例，碰到陌生壳就慢一些。

**Comment by yunboxtvj** [comment]
XYQhiker可以前后缀截取，也可以jousp写法。网上有一些案例，碰到陌生壳就慢一些，XBPQ只能前后缀截取。

**Comment by yunboxtvj** [comment]
XYQhiker可以前后缀截取，也可以jousp写法。网上有一些案例，碰到陌生壳就慢一些。XBPQ只能前后缀截取，XBPQ更简单，内置了模板，只要填写分类完事，其他自动补全。

**Comment by XiaoRanLiu3119** [comment]
感谢解惑，零零散散的概念总算是清晰了。真是遍地开花

**Comment by yunboxtvj** [comment]
这里面有XBPQ教程
https://github.com/dlgt7/TVbox-interface

**Comment by yunboxtvj** [comment]
这里面有XBPQ教程,XBPQ写源自学笔记
https://github.com/dlgt7/TVbox-interface

**Comment by yunboxtvj** [comment]
这里面有XBPQ教程,XBPQ写源自学笔记，
https://github.com/dlgt7/TVbox-interface

csp都是java爬虫，意思用java代码编译成jar包，软件调用jar包爬虫。
XBPQ和XYQhiker,就是jar包爬虫。他们借鉴了道长，特别XYQhiker写法差不多。XYQhiker爬虫代码加密了，XBPQ爬虫代码解密，属于不同jar包，需要缝合在一起。mt管理器暴力缝合jar包，多个jar包爬虫合并。

道长和猫影视，不需要爬虫，通过quick js直接运行js文件。
quick js跨平台，道长和猫影视，都可以苹果和windows上运行 。

**Comment by yunboxtvj** [comment]
四年前海阔浏览器诞生，道长加入编写道长js。猫影视开发出适配jar包，后来开源移植TVBox,各种Java爬虫出现。小黄瓜编写XBiubiu前后缀截取规则，XBiubiu是所有jar包规则鼻祖，后面规则都是改进。另外一个大佬开发XPath截取规则XPath。XPath后来加入了正则，解决嗅探问题，完善了筛选规则。

XYQhiker作者是香雅情大佬,首创全中文规则,引入海阔视界截取规则，后期代码融入阿里云和夸克云推送、磁力链接推送、ip代理。
XBPQ规则兼容了XBiubiu和XPath，这两种规则文件都能在XBPQ上运行。后期首创免嗅、嗅探词、图片代理、模板内置补全、简写规则。
TVBox不支持js,最早道长js放在服务器上，服务器T4规则。影魔大佬引入安卓版quick js，俊佬花两个月时间，适配道长js。两个月前爱老板修改quick js，猫爪大佬改了很多Bug,最后加入猫影视JS代码。

**Comment by yunboxtvj** [comment]
ext后面接json转义，也可以指向文件链接
https://github.com/yunboxtvj/TVBoxDIY

四年前海阔视界浏览器诞生，道长加入编写道长js。猫影视开发出适配jar包，后来开源移植TVBox,各种Java爬虫出现。小黄瓜编写XBiubiu前后缀截取规则，XBiubiu是所有jar包规则鼻祖，后面规则都是改进。另外一个大佬开发XPath截取规则XPath。XPath后来加入了正则，解决嗅探问题，完善了筛选规则。

XYQhiker作者是香雅情大佬,首创全中文规则,引入海阔视界截取规则，后期代码融入阿里云和夸克云推送、磁力链接推送、ip代理。
XBPQ规则兼容了XBiubiu和XPath，这两种规则文件都能在XBPQ上运行。后期首创免嗅、嗅探词、图片代理、模板内置补全、简写规则。
TVBox不支持js,最早道长js放在服务器上，服务器T4规则。影魔大佬引入安卓版quick js，俊佬花两个月时间，适配道长js。两个月前爱老板修改quick js，猫爪大佬改了很多Bug,最后加入猫影视JS代码。

**Comment by yunboxtvj** [comment]
ext后面接json转义，也可以指向文件链接
https://github.com/yunboxtvj/TVBoxDIY

四年前海阔视界浏览器诞生，道长加入编写道长js。猫影视开发出适配jar包，后来开源移植到TVBox播放器,各种Java爬虫出现。小黄瓜编写XBiubiu前后缀截取规则，XBiubiu是所有jar包规则鼻祖，其他java规则都是改进。另一位大佬开发XPath截取规则“XPath”。XPath引入正则，解决嗅探问题，完善了筛选规则。

XYQhiker作者是香雅情大佬,首创全中文规则,引入海阔视界截取规则。两种筛选模式，两种截取规则。后期代码融入阿里云和夸克云推送、磁力链接推送、ip代理。
XBPQ规则兼容了XBiubiu和XPath，这两种规则文件都能在XBPQ上运行。后期首创免嗅、嗅探词、图片代理、模板内置补全、简写规则。

TVBox不支持js,最早道长js放在服务器上，服务器T4规则。影魔大佬引入安卓版quick js，俊佬花两个月时间，适配道长js。两个月前爱老板修改quick js引擎，猫爪大佬改了很多Bug,增加猫影视JS代码。drpy.js文件，三天一升级，跟不上思路，一年后规则会大变。不管规则怎么变，视频网站采集cms系统,只有十家而已。

**Comment by XiaoRanLiu3119** [comment]
你这了解的也忒详细了,解我不少惑,信息量相当大

**Comment by yunboxtvj** [comment]
py好像是安卓py模拟，打包成aar文件

**Comment by yunboxtvj** [comment]
py好像是安卓py模拟，打包成aar文件。海阔视界本身就有py版本，道长加了一个js转海阔py文件。
https://github.com/dlgt7/TVbox-interface/blob/main/Pyramid%E6%B7%BB%E5%8A%A0%E6%95%99%E7%A8%8B.md

**Comment by yunboxtvj** [comment]
py好像是安卓py模拟，打包成aar文件。道长加了一个js转海阔py文件。js截取数组方式，转换成py数组截取和定位。
https://github.com/dlgt7/TVbox-interface/blob/main/Pyramid%E6%B7%BB%E5%8A%A0%E6%95%99%E7%A8%8B.md

**Comment by XiaoRanLiu3119** [comment]
有py的源么我感受看看

**Comment by yunboxtvj** [comment]
{"key":"py_cctv","name":"央视","type": 3,"api":"py_cctv","searchable": 0,"quickSearch":0,"filterable":1,"ext": "https://agit.ai/kvymin/TV/raw/branch/master/pyramid/py_cctv.py"},

**Comment by yunboxtvj** [comment]
Chaquopy安卓版本，好像是内置到aar包里面

**Comment by XiaoRanLiu3119** [comment]
上次打包py版本是如何测试的,用的什么源呢

**Comment by yunboxtvj** [comment]
https://agit.ai/kvymin/pyramid/raw/branch/master/config.json

**Comment by yunboxtvj** [comment]
https://agit.ai/kvymin/pyramid/raw/branch/master/config.json

**Comment by yunboxtvj** [comment]
打包的话就是apk B，github可以编译
https://github.com/yunboxtvj/TVBoxDIY
https://agit.ai/kvymin/pyramid/raw/branch/master/config.json

**Comment by yunboxtvj** [comment]
编译出来41M，用apktool m压缩下28M

**Comment by yunboxtvj** [comment]
编译出来41M，用apktool m压缩下28M
https://github.com/yunboxtvj/TVBoxDIY/actions/runs/6578341308

**Comment by XiaoRanLiu3119** [comment]
github和我自己打包一样，py那个arr包就10多兆

**Comment by yunboxtvj** [comment]
可以压缩，压缩减少了13M

**Comment by yunboxtvj** [comment]
https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/issues/30#issuecomment-1772967838

**Comment by yunboxtvj** [comment]
https://maximoff.su/apktool/?lang=zh

**Comment by XiaoRanLiu3119** [comment]
[v0.6_quickjs_20231023.zip](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/files/13068283/v0.6_quickjs_20231023.zip)
apktoolm压缩重打包会换签名,麻烦。
这版我将qjs还有后续tk版的提交集成了,tab不显示的清缓存重载会正常,用道长搜索还是闪退,别的我还没测试

**Comment by XiaoRanLiu3119** [comment]
闪退排除原本代码空指针后,新增的那些代码报错,看不太懂

**Comment by yunboxtvj** [comment]
签名可以用mt重新打包

**Comment by yunboxtvj** [comment]
签名可以用mt重新签名，压缩的话勾上api不变。闪退应该是缓存问题，新增加代码有改缓存。

**Comment by yunboxtvj** [comment]
签名可以用mt重新签名，ultrazip是压缩,勾上api就行。原版taka删除了增加代码，估计是有bug吧。确实有的会闪退，还是等作者修改。

**Comment by XiaoRanLiu3119** [comment]
没看见回退呢，是，等稳定一些

**Comment by yunboxtvj** [comment]
taka99缩率图搜索会闪退，文字搜索不会闪退。

**Comment by XiaoRanLiu3119** [comment]
道长js,https://gh-proxy.com/https://raw.githubusercontent.com/gaotianliuyun/gao/master/js.json,如你所说的改,,热搜随便搜一个,等一会就闪退了

**Comment by yunboxtvj** [comment]
我们的视频源是一样，两个软件都测试，搜索线程调30,有崩溃出现。

**Comment by yunboxtvj** [comment]
我们的视频源是一样，两个软件都测试，搜索线程调30,软件没有崩溃。
https://raw.githubusercontent.com/yunboxtvj/TVBoxDIY/main/box.json

**Comment by yunboxtvj** [comment]
我们的视频源是一样，两个软件都测试，搜索线程调30,软件没有崩溃。bill有些问题，jar包没有上传，晚上缝合一个jar包。好像有人把猫影视quick js，做成外挂jar包，任何软件都能用猫影视源。
https://raw.githubusercontent.com/yunboxtvj/TVBoxDIY/main/box.json

**Comment by yunboxtvj** [comment]
我们的视频源是一样，两个软件都测试，搜索线程调30,软件没有崩溃。好像有人把猫影视quick js，做成外挂jar包，任何软件都能用猫影视源。
https://gh-proxy.com/https://raw.githubusercontent.com/yunboxtvj/TVBoxDIY/main/box.json

**Comment by yunboxtvj** [comment]
我们的视频源是一样，两个软件都测试，搜索线程调30,软件没有崩溃。好像有人把猫影视quick js，做成外挂jar包，任何软件都能用猫影视源。
https://gh-proxy.com/https://raw.githubusercontent.com/yunboxtvj/TVBoxDIY/main/box.json
![Screenshot_20231024_120215](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/4ed05767-91b2-41f2-bc9a-f843e36722d0)

**Comment by yunboxtvj** [comment]
![Screenshot_20231024_123551](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/2e1bdf87-c374-4adc-950c-92ea08923c19)

**Comment by XiaoRanLiu3119** [comment]
刚试了确实,这多好啊

**Comment by yunboxtvj** [comment]
更新了一些源，明天归整下音乐站源。不折腾了站源，够用就可以。
https://gh-proxy.com/https://raw.githubusercontent.com/yunboxtvj/TVBoxDIY/main/box.json

**Comment by XiaoRanLiu3119** [comment]
我更新了下quickjs,测了一上午,目前道长和xqy的js目前没闪退情况,可以试试

**Comment by dessi-mo** [comment]
> ext后面接json转义，也可以指向文件链接 https://github.com/yunboxtvj/TVBoxDIY
> 
> 四年前海阔视界浏览器诞生，道长加入编写道长js。猫影视开发出适配jar包，后来开源移植到TVBox播放器,各种Java爬虫出现。小黄瓜编写XBiubiu前后缀截取规则，XBiubiu是所有jar包规则鼻祖，其他java规则都是改进。另一位大佬开发XPath截取规则“XPath”。XPath引入正则，解决嗅探问题，完善了筛选规则。
> 
> XYQhiker作者是香雅情大佬,首创全中文规则,引入海阔视界截取规则。两种筛选模式，两种截取规则。后期代码融入阿里云和夸克云推送、磁力链接推送、ip代理。 XBPQ规则兼容了XBiubiu和XPath，这两种规则文件都能在XBPQ上运行。后期首创免嗅、嗅探词、图片代理、模板内置补全、简写规则。
> 
> TVBox不支持js,最早道长js放在服务器上，服务器T4规则。影魔大佬引入安卓版quick js，俊佬花两个月时间，适配道长js。两个月前爱老板修改quick js引擎，猫爪大佬改了很多Bug,增加猫影视JS代码。drpy.js文件，三天一升级，跟不上思路，一年后规则会大变。不管规则怎么变，视频网站cms系统,只有十家而已，大部分是苹果cms的二次开发。

XBPQ有解密的java吗?
