### ISSUE TITLE
PY编译成功

### ISSUE THREAD

**Issue by yunboxtvj** [XiaoRanLiu3119/TVBoxOS-Mobile#28]
APK压缩后体积28M，PY文件测试正常。

https://wwpr.lanzout.com/iJsdv1bsjokj

https://github.com/yunboxtvj/TVBoxDIY/actions/runs/6517418273

**Comment by XiaoRanLiu3119** [comment]
有劳了🤙

**Comment by yunboxtvj** [comment]
不知道什么原因，github编译文件都很大。

**Comment by 283590** [comment]
安卓6.0.0手机安装包损坏

**Comment by yunboxtvj** [comment]
https://github.com/yunboxtvj/TVBoxDIY/actions/runs/6652309115

**Comment by 283590** [comment]
| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月26日 17:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [XiaoRanLiu3119/TVBoxOS-Mobile] PY编译成功 (Issue #28) |

https://github.com/yunboxtvj/TVBoxDIY/actions/runs/6652309115

**Comment by 283590** [comment]
只能空壳子







***@***.***
***@***.***



---- 回复的原邮件 ----
发件人 ***@***.***>日期 2023年10月26日 17:49 收件人 ***@***.***>抄送至 ***@***.***>***@***.***>主题 Re: [XiaoRanLiu3119/TVBoxOS-Mobile] PY编译成功 (Issue #28)
https://github.com/yunboxtvj/TVBoxDIY/actions/runs/6652309115

**Comment by yunboxtvj** [comment]
本地接口不能输入吗，网络接口有问题吗

**Comment by 283590** [comment]
就是接口点击就是出现了上面的图片



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月27日 16:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [XiaoRanLiu3119/TVBoxOS-Mobile] PY编译成功 (Issue #28) |

本地接口不能输入吗，网络接口有问题吗
