### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by AlanTse1314** [XiaoRanLiu3119/TVBoxOS-Mobile#29]
建议直播改成这样，播放器建议增加长按左右滑动改变倍数播放的倍数
![B3C4CFD3-24C3-4222-B8C0-638E8984B168](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/88262891/e492e2f9-a0ce-4f63-89a2-6311c7491116)
![D661CB16-FEB0-432F-91A4-341ED59FC264](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/88262891/51cc11b8-850c-4bb8-8b06-33e4b8ebe7d1)
![DFC50A30-9591-49C5-B2E9-9DADFE1CA94B](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/88262891/859ddf54-cde2-4ebb-97a3-a080cb4f64fc)

**Comment by XiaoRanLiu3119** [comment]
影迷的直播是目标,不过摸鱼不好开发,得等等
