### ISSUE TITLE
建议改个包名 以便共存

### ISSUE THREAD

**Issue by ju0632** [XiaoRanLiu3119/TVBoxOS-Mobile#30]
建议改个包名 以便共存

**Comment by XiaoRanLiu3119** [comment]
有这想法 下版看情况

**Comment by yunboxtvj** [comment]
apktool m压缩下体积，减少10M左右。
![Screenshot_20231018_115548_edit_9070226461115](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/92b4d041-f885-42d9-b6a4-1104e6d1ab4a)

**Comment by XiaoRanLiu3119** [comment]
> Apktool M压缩下体积，减少10M左右。
> 
> https://maximoff.su/apktool/?lang=zh
> 
> ![Screenshot_20231018_115548_edit_9070226461115](https://user-images.githubusercontent.com/146441988/276100756-92b4d041-f885-42d9-b6a4-1104e6d1ab4a.jpg)

下次试试这

**Comment by yunboxtvj** [comment]
加一个熄屏播放功能,听小说一般都是熄屏。

**Comment by XiaoRanLiu3119** [comment]
> 加一个熄屏播放功能,听小说一般都是熄屏。

更想加个后台播放，不过要往后排

**Comment by yunboxtvj** [comment]
quick js 闪退bug好像修复了

**Comment by XiaoRanLiu3119** [comment]
> quick js 闪退bug好像修复 https://github.com/takagen99/Box

你在哪些群里有俊佬他们么

**Comment by yunboxtvj** [comment]
不清楚群号，高应该知道群号。大部分tg上，很少用tg。

**Comment by XiaoRanLiu3119** [comment]
好的猫爪大佬我听你说的应该知道哪个了，爱老板没对上号

**Comment by XiaoRanLiu3119** [comment]
我接触的时间短，各位大佬也都不认识

**Comment by yunboxtvj** [comment]
手机端没有必要太复杂，加上猫影视和py。估计软件大小，30M左右。直播感觉没必要整，各种格式适配太麻烦，软件体积会太大。

**Comment by q7954** [comment]
可以加486722328道长的Q群，猫爪爱佬饭太硬他们都在
