### ISSUE TITLE
你好，播放界面能否加入q版的音轨和字幕

### ISSUE THREAD

**Issue by q7954** [XiaoRanLiu3119/TVBoxOS-Mobile#31]
还有看频道有人听有声小说，我听了下暂不支持后台播放，近期或后期能否增加后台播放

**Comment by XiaoRanLiu3119** [comment]
.6版本有字幕,音轨下个版本改,后台播放应该会加

**Comment by AlanTse1314** [comment]
这个长按左右滑动改变倍数播放好像没有呀
![23F1629F-52FB-48EE-9B99-9CBF3B406666](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/88262891/caf8f717-5358-4c90-9eb2-1f2ba0217156)

**Comment by XiaoRanLiu3119** [comment]
> 这个长按左右滑动改变倍数播放好像没有呀 ![23F1629F-52FB-48EE-9B99-9CBF3B406666](https://user-images.githubusercontent.com/88262891/277581658-caf8f717-5358-4c90-9eb2-1f2ba0217156.jpeg)

这个不加

**Comment by AlanTse1314** [comment]
为啥呀，那加个竖屏吧
![8E9DBCB6-7BC5-4561-A792-5CEA0D27367B](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/88262891/f77748bf-7b2d-4b5a-b67e-930505e96d6f)

**Comment by XiaoRanLiu3119** [comment]
> 为啥呀，那加个竖屏吧 ![8E9DBCB6-7BC5-4561-A792-5CEA0D27367B](https://user-images.githubusercontent.com/88262891/277606308-f77748bf-7b2d-4b5a-b67e-930505e96d6f.jpeg)

有优先度更高的,竖屏在下版本加

**Comment by XiaoRanLiu3119** [comment]
后台播放下版本加,通知栏的控制不一定
