### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by GHVIP** [XiaoRanLiu3119/TVBoxOS-Mobile#32]
1.首页添加收藏按钮
2.直播源和点播源能分开订阅
3.全屏选集能选择倒序
4.能识别短剧竖屏全屏播放

**Comment by XiaoRanLiu3119** [comment]
1、2后面再说。,3、4下版本加,横竖屏得自己切换

**Comment by GHVIP** [comment]
增加两点建议：
5.能小窗播放
6.订阅源添加完成后可再次重命名

**Comment by XiaoRanLiu3119** [comment]
4和6已添加到0.7.1,传到release了

**Comment by GHVIP** [comment]
很高兴，提的建议基本都被采纳实现，大体功能确实都已实现，现在感觉已经很不错，希望越做越好。
如果非要再提点建议的话:
7.希望能添加小窗播放按钮，能通过按钮点击切换小窗播放
8.非全屏界面，选集展开后的界面也能添加个倒序按钮会更好

还有就是希望1.首页添加收藏按钮 也能早日实现

**Comment by GHVIP** [comment]
增加一点建议:
9.长按倍数的提示过段时间可自动隐藏

**Comment by GHVIP** [comment]
10.直播源历史记录无法删除，删除后退出再进入后还有
11.播放链接的输入框的记录能不能自动清空，省的下次还得删掉在输入，如果为了方便下次接着播放，是不是考虑也加个历史记录

**Comment by XiaoRanLiu3119** [comment]
10下版本修下
11那个是手机剪切板的链接,不是记录,我看看加个提示,避免混淆。链接播放后在历史记录也能找到

**Comment by GHVIP** [comment]
12.竖屏全屏选集界面是不是不要占满全屏会好一点，这样可以点击播放界面隐藏选集界面
