### ISSUE TITLE
11

### ISSUE THREAD

**Issue by 283590** [XiaoRanLiu3119/TVBoxOS-Mobile#34]
安卓6.0.0手机安装包损坏

**Comment by XiaoRanLiu3119** [comment]
安卓7.0以下得替换minSdkVersion 24 自行打包测试

**Comment by 283590** [comment]
不会弄，放弃了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月26日 13:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [XiaoRanLiu3119/TVBoxOS-Mobile] 11 (Issue #34) |

安卓7.0以下得替换minSdkVersion 24 自行打包测试

**Comment by XiaoRanLiu3119** [comment]
[TVBoxMobile_v0.7_安卓6.zip](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/files/13175764/TVBoxMobile_v0.7_.6.zip)
