### ISSUE TITLE
直播，竖屏切全屏，直播没有画面，切换竖屏也没有

### ISSUE THREAD

**Issue by slasjh** [XiaoRanLiu3119/TVBoxOS-Mobile#35]
必须点击暂停旁边的刷新，才有画面。系统/ijk硬解/EXO都是一样

使用IJK软解，可以全屏和竖屏播放

**Comment by XiaoRanLiu3119** [comment]
看直播还是老实用ijk吧

**Comment by slasjh** [comment]
建议直播时直接切换到IJK软解

**Comment by slasjh** [comment]
另外，请问老大，摸索了很久，都解决不了，如何内置订阅？

**Comment by XiaoRanLiu3119** [comment]
![image](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/62411322/5cca9992-85e6-436f-b933-57af31917c52)

**Comment by slasjh** [comment]
这个是源文件，不太懂。使用mt打开apk，如何变更默认源

**Comment by XiaoRanLiu3119** [comment]
没提供内置的静态文件,或者研究下如何使用github打包https://github.com/yunboxtvj/TVBoxDIY

**Comment by slasjh** [comment]
安装mbox后在"订阅管理-添加订阅"页面，地址栏直接内置地址，然后手动添加，这个可以实现吗？

**Comment by yunboxtvj** [comment]
mt管理搜索api_url，Androidx.base 三个api文件，填写网址就可以。     
 
const-string v0, "api_url" const-string v1, "网址"

**Comment by yunboxtvj** [comment]
小窗口播放的bug,直播问题小窗口有bug

**Comment by yunboxtvj** [comment]
mt管理搜索api_url，Androidx.base 三个api文件，其中一个填写网址就可以。

const-string v0, "api_url" const-string v1, "网址"
![Screenshot_20231027_175333](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/9b48dc44-8cee-4d29-b585-d753b23e864b)
![Screenshot_20231027_175409](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/a05775bb-a580-4efc-a888-04a9a60e0c23)

**Comment by yunboxtvj** [comment]
有备份数据功能，备份的数据在tvbox_backup文件夹下。

**Comment by yunboxtvj** [comment]
多仓链接
搜索 dialog_input_subsription
字符常量池找到hint改成text
找到“地址 例: https://...”改成自己网址

**Comment by slasjh** [comment]
thanks very much .我看见有更新版本0.7，我去试试
