### ISSUE TITLE
0.7版bug

### ISSUE THREAD

**Issue by jllyzjs** [XiaoRanLiu3119/TVBoxOS-Mobile#36]
直播源配置代码优化
之后
接口文件内直播
"lives":[
{"group": "央视","channels": [
{"name":"TVMovie","urls":["https://"]},
代码不支持，直播提示崩溃。

**Comment by piapiapiapapapa** [comment]
![IMG_20231027_224948.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/105154711/cb96f9af-c264-4c4b-b076-af42688328f7)

深色主题下，添加订阅弹窗界面基本看不清内容，因为是黑背景配黑色字体和蓝色字体，对比太不明显。

**Comment by lover520f** [comment]
希望增加一个一键获取token功能，另外设置中的分类选项位置较低，比如倍速选项2倍可以看到.3倍只能看到一半.希望放在屏幕中央，方便选择

**Comment by XiaoRanLiu3119** [comment]
什么源整这格式的直播配置

**Comment by XiaoRanLiu3119** [comment]
> ![IMG_20231027_224948.jpg](https://user-images.githubusercontent.com/105154711/278680289-cb96f9af-c264-4c4b-b076-af42688328f7.jpg)
> 
> 深色主题下，添加订阅弹窗界面基本看不清内容，因为是黑背景配黑色字体和蓝色字体，对比太不明显。

深色用的多嘛，先用着，下版本我调调颜色

**Comment by XiaoRanLiu3119** [comment]
> 希望增加一个一键获取token功能，另外设置中的分类选项位置较低，比如倍速选项2倍可以看到.3倍只能看到一半.希望放在屏幕中央，方便选择

看看截图呗，没太理解

**Comment by XiaoRanLiu3119** [comment]
> ![Screenshot_20231027-230015](https://user-images.githubusercontent.com/6552899/278688916-bd732ec6-7fdb-454b-a656-b7016443db50.jpg) 就是这样的

这。。。见所未见啊，啥手机，是被导航栏挡住了么

**Comment by yunboxtvj** [comment]
token应该就是阿里网盘获取，阿里云推送代码

**Comment by yunboxtvj** [comment]
token应该就是阿里网盘获取，影视TV有阿里云推送代码

**Comment by XiaoRanLiu3119** [comment]
> token应该就是阿里网盘获取，影视TV有阿里云推送代码

不太想搞这个，看看吧

**Comment by lover520f** [comment]
> > ![Screenshot_20231027-230015](https://user-images.githubusercontent.com/6552899/278688916-bd732ec6-7fdb-454b-a656-b7016443db50.jpg) 就是这样的
> 
> 这。。。见所未见啊，啥手机，是被导航栏挡住了么

不是导航键，是已经到手机最低部了，一加8T ，希望能把这个窗口放在屏幕中间，如果就是我手机的问题，当我没说，大家没问题就行，哈哈😄

**Comment by XiaoRanLiu3119** [comment]
> 推送磁力链接，云盘token获取是在一起的，应该是可以复制代码

影视没看到这功能呢,下周看看代码

**Comment by XiaoRanLiu3119** [comment]
> > > ![Screenshot_20231027-230015](https://user-images.githubusercontent.com/6552899/278688916-bd732ec6-7fdb-454b-a656-b7016443db50.jpg) 就是这样的
> > 
> > 
> > 这。。。见所未见啊，啥手机，是被导航栏挡住了么
> 
> 不是导航键，是已经到手机最低部了，一加8T ，希望能把这个窗口放在屏幕中间，如果就是我手机的问题，当我没说，大家没问题就行，哈哈😄

没事，有的话估计都会提，附近要是有一加店我就溜达溜达，正好没用过

**Comment by yunboxtvj** [comment]
https://github.com/FongMi/CatVodSpider/blob/main/app/src/main/java/com/github/catvod/spider/Ali.java

**Comment by yunboxtvj** [comment]
https://github.com/FongMi/CatVodSpider/blob/main/app/src/main/java/com/github/catvod/spider/Ali.java
https://github.com/FongMi/CatVodSpider/blob/main/app/src/main/java/com/github/catvod/spider/AList.java

**Comment by XiaoRanLiu3119** [comment]
还是不搞app上了吧

**Comment by yunboxtvj** [comment]
考虑加上接口文件下载，一键转为本地包。

**Comment by q7954** [comment]
> > ![Screenshot_20231027-230015](https://user-images.githubusercontent.com/6552899/278688916-bd732ec6-7fdb-454b-a656-b7016443db50.jpg) 就是这样的
> 
> 这。。。见所未见啊，啥手机，是被导航栏挡住了么

小米没有这问题…
