### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by jllyzjs** [XiaoRanLiu3119/TVBoxOS-Mobile#38]
①在首页刷新接口链接里的更新内容，无效。
②自动转屏，竖屏视频自动转竖屏。
③多个仓库都显示出来并且能编辑和复制，删除，刷新更新内容。
④播放时悬浮窗口在桌面
⑤直播无预告

**Comment by yunboxtvj** [comment]
悬浮窗口要修改安卓自带窗口，自带悬浮窗口不可以调窗口大小。影视仓是抄github悬浮窗口代码，渲染模式为s时候，播放器会黑屏，悬浮窗口改了很久。

**Comment by XiaoRanLiu3119** [comment]
订阅的编辑有时间我弄,自动转竖屏有现成代码的话我再看看,其他暂时不考虑

**Comment by yunboxtvj** [comment]
接口更新，需要清空缓存重启app，设置里有清空缓存。

**Comment by yunboxtvj** [comment]
播放器修改截图
![Screenshot_20231031_142316_edit_35185659356609](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/415cddae-745b-4bf9-9d3f-08491ecfedff)

**Comment by yunboxtvj** [comment]
dns参数不清楚，腾讯是多少，晚上再看看。仿播放器参数，添加数据就行。
![Screenshot_20231031_143425](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/17eb477c-71b9-4aa9-8ebf-4cbf14e291ac)

**Comment by XiaoRanLiu3119** [comment]
小视频自动竖屏和订阅重命名已更新,release中传了0.7.1测试版,可以试试

**Comment by jllyzjs** [comment]
> 小视频自动竖屏和订阅重命名已更新,release中传了0.7.1测试版,可以试试

试过了OK

**Comment by yunboxtvj** [comment]
悬浮窗口
https://github.com/puyang1017/EasyFloat

**Comment by yunboxtvj** [comment]
影视仓悬浮窗口
https://github.com/puyang1017/EasyFloat

![Screenshot_20231031_190321](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/c594458d-9c63-4cee-bcc8-95724a5b259a)

**Comment by yunboxtvj** [comment]
https://github.com/ZhangJiaLei123/DemoFloatingWindow

**Comment by yunboxtvj** [comment]
看了一下海阔视界站源规则，app模式和网页模式，网页模式规则比较容易，app总是解析失败。

**Comment by yunboxtvj** [comment]
看了一下海阔视界站源规则，app模式和网页模式，网页模式规则比较容易，app总是解析失败。好像两个模板，Q模板和道长模板。

**Comment by yunboxtvj** [comment]
DR模板一级和二级分开匹配，有些不适应，二级内置模板，很多都要修改，反而浪费很多时间。
一级
{"解析":".myui-vodlist&&li;h4&&Text;.lazyload&&data-original;.pic-tag||.pic-text&&Text;a&&href","名称":"myui-vodlist","是否有二级":true,"免责":false}
二级
{"解析":{"title":".myui-content__detail,0&&.title&&Text","img":".lazyload&&data-original","url":".lazyload&&data-original","desc":".myui-content__detail&&.data&&Text","content":"#rating&&Text","tabs":"body&&.myui-panel__head&&h3","tab_text":".title&&Text","lists":"#playlist1&&li","tab_id":""},"名称":"首图2","免嗅":false,"需要魔断":false,"动态最新章节":true}

**Comment by XiaoRanLiu3119** [comment]
> ④播放时悬浮窗口在桌面

release1.0测试版中更新了小窗播放,可以体验下,没啥问题将是下个正式版

**Comment by yunboxtvj** [comment]
大佬速度真快，这么快就1.0版本 。

**Comment by XiaoRanLiu3119** [comment]
> 大佬速度真快，这么快就1.0版本 。

-_-, 你不也说没啥功能了,也不能卡在0.8,后面就跟随真大佬更新了

**Comment by yunboxtvj** [comment]
画中画不能调窗口大小，设置两个窗口大小，设置里自己选大小。现在的窗口高度不够，宽度问题不大。

**Comment by XiaoRanLiu3119** [comment]
> 画中画不能调窗口大小，设置两个窗口大小，设置里自己选大小。现在的窗口高度不够，宽度问题不大。

抄的tk,系统的画中画,拖拽就是系统差异性了,小米拖拽放大缩小都正常

**Comment by yunboxtvj** [comment]
剩下一个token推送功能，软件功能差不多了。https://github.com/nbwzlyd/TVBoxOS/commit/d20106cad6e04d4d367a47ddba2d7ab445107c7e
