### ISSUE TITLE
mbox0.7横竖屏切换更新的非常及时，对短剧超级友好，点赞

### ISSUE THREAD

**Issue by slasjh** [XiaoRanLiu3119/TVBoxOS-Mobile#39]
打开直播，默认使用EXO播放器，造成直播无法观看，必须要手段切换IJK播放器才能正常播放。
mp或mt怎么修改apk默认设置，将播放器设置为ijk，安全dns设置为腾讯。

ps：另外广告拦截可以作为下一版本亮点

**Comment by yunboxtvj** [comment]
修改com/github/tvbox/osc/base/App，添加修改过， 代码忘的差不多了，不如直接编译简单

**Comment by XiaoRanLiu3119** [comment]
下次我将默认设置写进App.java,像tk版那样

**Comment by yunboxtvj** [comment]
dns参数不清楚，腾讯是多少，晚上再看看。仿播放器参数，添加数据就行。
![Screenshot_20231031_143425](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/1b2248db-1576-4089-a2e6-b2d69159687e)

**Comment by yunboxtvj** [comment]
播放器如截图修改就可以
![Screenshot_20231031_142316_edit_35185659356609](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/3cada340-4004-4946-80b4-c187bb61f9e9)

**Comment by XiaoRanLiu3119** [comment]
release中传了0.7.1测试版,小视频全屏自动是竖全屏,可以试下

**Comment by yunboxtvj** [comment]
好的，晚上再下载吧

**Comment by XiaoRanLiu3119** [comment]
> 好的，晚上再下载吧

洛雪手机版最近用不了了,猫的音乐源是真及时

**Comment by yunboxtvj** [comment]
音乐源海阔视界有个插件很牛，可以复制各个音乐网站，音乐帐号收藏

**Comment by yunboxtvj** [comment]
音乐源海阔视界有个插件很牛，可以复制各个音乐网站，甚至复制音乐帐号收藏。海阔视界道长仓库有插件

**Comment by yunboxtvj** [comment]
音乐源海阔视界有个插件很牛，可以复制各个音乐网站，甚至复制音乐帐号收藏。海阔视界道长仓库有插件
![Screenshot_20231031_154034](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/0847f96a-50a7-40cf-9ce9-31bc0f5718eb)

**Comment by yunboxtvj** [comment]
复制音乐帐号全部歌单
![Screenshot_20231031_154331](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/f7a38e85-c81b-44a9-87c7-43140563fa20)

**Comment by yunboxtvj** [comment]
复制音乐帐号全部歌单
![Screenshot_20231031_154511](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/1c3945fc-b3f6-450c-8bc5-e6866ded2ea4)
![Screenshot_20231031_154331](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/1ac1c63c-4bad-4f07-9b42-2fcac329b2c7)

**Comment by XiaoRanLiu3119** [comment]
> 海阔视界有个插件很牛，复制音乐帐号歌单。海阔视界道长仓库有插件， ![Screenshot_20231031_154034](https://user-images.githubusercontent.com/146441988/279294850-0847f96a-50a7-40cf-9ce9-31bc0f5718eb.jpg)

这是什么软件,海阔视界么

**Comment by yunboxtvj** [comment]
海阔视界，导入道长仓库口令
￥home_rule_url￥http://hiker.nokia.press/hikerule/rulelist.json?id=1094

**Comment by yunboxtvj** [comment]
海阔视界官方下载
https://haikuo.lanzoui.com/u/GoldRiver

**Comment by yunboxtvj** [comment]
主页我的小程序，找到道长仓库，搜索yes就行，导入规则就能用。
![Screenshot_20231031_160901_edit_41518467751997](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/a8975d23-7a58-450b-bf9c-0767b729c1c1)

**Comment by yunboxtvj** [comment]
![Screenshot_20231031_161321_com example hikerview_edit_41765340319147](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/e00efc04-327b-4348-8840-a0d14e5617e0)
![Screenshot_20231031_161651_com example hikerview_edit_41973111026928](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/063befea-1bc0-47b3-a72d-6ca5a7ce0aea)
![Screenshot_20231031_161815](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/cbeebd6a-4219-49c5-a61b-218ab544e9e5)

**Comment by XiaoRanLiu3119** [comment]
感谢看到了,这回有的听了

**Comment by yunboxtvj** [comment]
找到海阔内部文件，修改下就能复制收藏大部分歌单

**Comment by yunboxtvj** [comment]
主页搜索比较方便
![Screenshot_20231031_164142_edit_43455461216285](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/732dcc7c-8c66-42bd-93fc-7b4283d5cbd8)
![Screenshot_20231031_164100](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/a26781e7-84ab-4735-986c-51c42dacd970)

**Comment by XiaoRanLiu3119** [comment]
我在研究怎么能搞自己的歌单进去

**Comment by yunboxtvj** [comment]
有个简单音乐，也是旧港人生写的

**Comment by yunboxtvj** [comment]
一个月前修改了海阔文件，导入了一些歌单，很久不用忘记了。

**Comment by yunboxtvj** [comment]
基本上搞定了
https://music.163.com/#/user/home?id=342371680
{"NetEase":[342371680]}

**Comment by yunboxtvj** [comment]
基本上搞定了，海阔简单音乐.js
https://music.163.com/#/user/home?id=342371680
{"NetEase":[342371680]}
![Screenshot_20231031_182702](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/ab19a00b-02c3-4bb6-b74e-88881e2df0a0)

**Comment by yunboxtvj** [comment]
DNS改成腾讯，播放器改成IJK播放器
https://github.com/yunboxtvj/TVBoxOS-Mobile/actions/runs/6706126879

**Comment by yunboxtvj** [comment]
基本上搞定了，找到简单音乐.js
https://music.163.com/#/user/home?id=342371680

{"NetEase":[342371680],"BuildList":[],"BuildMusic":{"NetEase":[{"name":"治愈纯音乐｜人间温柔 聆听时光静好","picUrl":"https://p1.music.126.net/vooe4WE0lNgH1Z3CS8rBlg==/109951168636658829.jpg","mid":8436750387}],"Tencent":[],"Kwmusiccar":[],"Kugou":[],"Migu":[]}}

![Screenshot_20231031_182702](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146441988/ab19a00b-02c3-4bb6-b74e-88881e2df0a0)

**Comment by yunboxtvj** [comment]
yes歌单收藏,简单里面收录，至于导入特定帐号，仔细看简单音乐.js文件

**Comment by yunboxtvj** [comment]
NetEase指定帐号，导入帐号id完事，yes里面有收藏，简单里面的分享，就是复制地址，地址导入到歌单里面。

**Comment by yunboxtvj** [comment]
美债好像要爆了，外流资金要回流。中美会议之前，A股肯定会跌一波，基金重仓的医药和化工股，基金高位套牢。中美会谈结束，医药股拉升。
