### ISSUE TITLE
数据库DB文件不存在

### ISSUE THREAD

**Issue by yunboxtvj** [XiaoRanLiu3119/TVBoxOS-Mobile#41]
导入多仓接口和仓库时候，备份数据提示这个问题，备份文件夹和俊版重合了。

**Comment by jllyzjs** [comment]
不观看视频使用，你让它备份什么？
随意观看视频之后再备份

**Comment by yunboxtvj** [comment]
设置和接口数据都储存在Hawk,影视数据存储在数据库里，备份提示DB文件不存在。

**Comment by XiaoRanLiu3119** [comment]
订阅没用数据库,只添加订阅应该没法备份,观看历史和收藏都走数据库了,有任何历史和收藏都可以备份。
重合问题只要不恢复用俊版时的备份应该问题不大,情况多了我再将俊版的历史接口转换成线路。
最开始就没考虑存储多仓,只提供导入了

**Comment by yunboxtvj** [comment]
二次萌网址又变了，这些站源二个月换一个域名。

**Comment by yunboxtvj** [comment]
懒的折腾用XBPQ搞定搜索

**Comment by yunboxtvj** [comment]
写电影鱼三种规则，可以做对比。年代、地区、类型，道长和XYQhiker写法有些小区别。

**Comment by yunboxtvj** [comment]
偷懒没写播放线路替换词，XYQhiker和道长，线路替换和排序不太方便。

**Comment by yunboxtvj** [comment]
偷懒没写播放线路替换词，XYQhiker和道长，线路替换和排序不太方便。年份比较难定位,道长js地区.video-info-aux&&a:eq(-1)&&Text。

**Comment by yunboxtvj** [comment]
偷懒没写播放线路替换词，XYQhiker和道长，线路替换和排序不太方便。年份比较难定位。

地区.video-info-aux&&a:eq(-1)&&Text。
年代.video-info-aux&&a:eq(-2)&&Text。

**Comment by yunboxtvj** [comment]
偷懒没写播放线路替换词，XYQhiker和道长，线路替换和排序不太方便，年代比较难定位。

道长JS
地区.video-info-aux&&a:eq(-1)&&Text。
年代.video-info-aux&&a:eq(-2)&&Text。

XYQhiker
年代div.video-info-aux&&a,-2&&Text。
地区div.video-info-aux&&a,-1&&Text。

**Comment by yunboxtvj** [comment]
开始学写py规则，py案例比较多了。
https://agit.ai/lanhaidixingren/Tvbox/src/branch/master/py

**Comment by yunboxtvj** [comment]
py好多播放不出来，不知道是不是规则有错误。
