### ISSUE TITLE
ijkplayer不支持http状态码308重定向

### ISSUE THREAD

**Issue by bgylde** [XiaoRanLiu3119/TVBoxOS-Mobile#49]
http://cntv.lat/tv/live.php?auth=231110&id=cctv1HD
返回状态码308，但是无法重定向导致播放失败。请问一下tvbox的ijkplayer源码在哪里有，官方的ijkplayer已经找到修复308问题的方法，但是没有native_setDot方法，本地只能暂时屏蔽这个方法调用。

**Comment by XiaoRanLiu3119** [comment]
player模块有ijk相关的so包和java代码,至于用的哪个版本源码和如何修复我就不懂了
