### ISSUE TITLE
设置界面弹窗显示不全

### ISSUE THREAD

**Issue by M17764017422** [XiaoRanLiu3119/TVBoxOS-Mobile#52]
https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/31874069/ba368b8d-29b2-4c94-af47-52f817d50efa

弹窗底部明显不全，虽然不影响使用就是了
另外整体上弹窗交互逻辑太坑了，随便一动就消失了，打开通知栏截图都不行，必须录屏才行。

**Comment by XiaoRanLiu3119** [comment]
不会也是1+的手机吧

**Comment by M17764017422** [comment]
> 不会也是1+的手机吧

不是，是小米的，上次反馈提供过系统信息的。

**Comment by XiaoRanLiu3119** [comment]
选择弹窗原版有隐藏标题栏,后续某个版本去掉。没时间挨个找,什么型号我找来测测

**Comment by M17764017422** [comment]
> 选择弹窗原版有隐藏标题栏,后续某个版本去掉。没时间挨个找,什么型号我找来测测

> 选择弹窗原版有隐藏标题栏,后续某个版本去掉。没时间挨个找,什么型号我找来测测
确实有个隐藏控件，根据不同的系统设置改变大小。
![Screenshot_2023-11-17-23-30-51-889_com.miui.home.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/31874069/2b925df1-69ec-49de-93da-b07b465140d4)


![Screenshot_2023-11-18-00-23-16-265_com.github.tvbox.osc.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/31874069/30815b1c-87e2-4631-8117-dc7c3c82ba4a)
上面显示是全屏手势模式

![Screenshot_2023-11-18-00-20-15-956_com.github.tvbox.osc.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/31874069/54d4a4fd-2513-4bea-ad32-35d84017bd77)
这是经典按键模式的大小明显挤占显示空间

**Comment by M17764017422** [comment]
> 选择弹窗原版有隐藏标题栏,后续某个版本去掉。没时间挨个找,什么型号我找来测测
确实有个隐藏控件，根据不同的系统设置改变大小。
![Screenshot_2023-11-17-23-30-51-889_com.miui.home.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/31874069/2b925df1-69ec-49de-93da-b07b465140d4)


![Screenshot_2023-11-18-00-23-16-265_com.github.tvbox.osc.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/31874069/30815b1c-87e2-4631-8117-dc7c3c82ba4a)

![Screenshot_2023-11-18-00-20-15-956_com.github.tvbox.osc.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/31874069/54d4a4fd-2513-4bea-ad32-35d84017bd77)
上面显示是全屏手势模式

![Screenshot_2023-11-18-00-23-16-265_com.github.tvbox.osc.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/31874069/c77a760a-60f6-4e1c-9b45-c06995152912)
这是经典按键模式的大小明显挤占显示空间

**Comment by XiaoRanLiu3119** [comment]
帮忙看下“我的”页面的关于弹窗，和详情页面的影片详情弹窗是否有这情况。这些弹窗应该处理好了

**Comment by XiaoRanLiu3119** [comment]
我的小米倒是没这情况，不过不止一个这情况了，我合计下，不动q版代码去额外处理了，将选择弹窗居中显示

**Comment by M17764017422** [comment]
看了，其它地方没问题，只有设置界面的弹窗，会启用全屏显示模式，正常情况这时候按键应该收起来才对

https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/31874069/0c274661-272b-4b71-803e-3c393e3e2bd7
