### ISSUE TITLE
大佬能否更新下嗅探和quickjs等，后期app能否兼容鸿蒙5.0以上

### ISSUE THREAD

**Issue by q7954** [XiaoRanLiu3119/TVBoxOS-Mobile#53]
我看了下最近一个多月更新貌似都没更新嗅探qquickjs等，我看takagen他们都已经更新过也用了一个多月了

**Comment by XiaoRanLiu3119** [comment]
我试过，但q和tk版还是有些不同，动的代码太多，我还不会qjs，改坏了修不了，随q版同步稳一点.
要是鸿蒙next就没法兼容了

**Comment by q7954** [comment]
我好像看网上说flutter写的好像以后能兼容…

**Comment by yunboxtvj** [comment]
q版退回原来代码，tk版quick修复了崩溃问题。

**Comment by yunboxtvj** [comment]
小米的 HyperOS 和 Vivo 也宣布即将发布自研系统，未来安卓开发软件，全部要重新开发。

**Comment by XiaoRanLiu3119** [comment]
> q版退回原来代码，tk版quick修复了崩溃问题。

q版还是新版的qjs呢,回退又合并了,没看到往外的回退commit
