### ISSUE TITLE
关于本地文件访问的建议

### ISSUE THREAD

**Issue by M17764017422** [XiaoRanLiu3119/TVBoxOS-Mobile#58]
能不能只授权并记住一个文件夹，每次直接打开这个文件夹
![Screenshot_2023-11-21-14-54-53-882_com.github.tvbox.osc.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/31874069/a330d272-a94a-4823-9ddc-303eb91f738c)
系统目录太多了，每次添加本地接口都要翻半天。

![Screenshot_2023-11-20-17-01-10-183_io.legado.app.release.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/31874069/34df9fd2-511a-419c-8e96-7079fb1a15a0)
![Screenshot_2023-11-21-14-05-36-997_com.google.android.documentsui.jpg](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/31874069/3cbf8671-364d-4daa-aa8d-ded81d22024f)

改成上面这样更安全也更方便。

**Comment by XiaoRanLiu3119** [comment]
本地包用的不多,不单独搞个设置项了,只记住上次选择的目录吧,能方便一些吧

**Comment by M17764017422** [comment]
都是成熟的开源代码，应该不会太麻烦，当然只要记住上次的也行，以后方便的话我提一下补丁
