### ISSUE TITLE
@headers=格式的请求头参数里的/会变成双的，造成图片没法正常显示，Q版的修了没有这种问题。

### ISSUE THREAD

**Issue by lzk23559** [XiaoRanLiu3119/TVBoxOS-Mobile#61]
[
![Screenshot_20231124_130319](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/78088047/f67b98e9-47f9-4c96-82c2-f7d369f403f2)
](url)

**Comment by XiaoRanLiu3119** [comment]
爱看机器人站点的图片么，下周看看
