### ISSUE TITLE
播放哔嘀的磁力软件会崩溃，

### ISSUE THREAD

**Issue by lzk23559** [XiaoRanLiu3119/TVBoxOS-Mobile#63]
如题，播放哔嘀的mkv磁力软件会崩溃，原因是mkv上有位图字幕，需要使用影魔的最新ijk解码so文件才行，https://github.com/CatVodTVOfficial/TVBoxOSC_ijkplayer/tree/main
更新后顺便修复下满屏字幕问题

ed2k://|file|Story.of.Kunning.Palace.2023.EP01.HD1080P.X264.AAC.Mandarin.CHS.BDYS.mkv|655354777|39d8e9973941101001f73ddd69c8c5d0|/

ed2k://|file|Story.of.Kunning.Palace.2023.EP02.HD1080P.X264.AAC.Mandarin.CHS.BDYS.mkv|758210345|c5d4cf7af47721ae535678e96e932251|/

**Comment by XiaoRanLiu3119** [comment]
之后再考虑替换
