### ISSUE TITLE
很高兴使用您开发的软件

### ISSUE THREAD

**Issue by XiyunYi** [XiaoRanLiu3119/TVBoxOS-Mobile#64]
您能增加一个1.25倍速么！

**Comment by XiaoRanLiu3119** [comment]
好的，后面版本加，我没用到还以为没啥用呢

**Comment by jjjzcyt** [comment]
> 好的，后面版本加，我没用到还以为没啥用呢

能添加复制播放链接的按钮吗

**Comment by XiaoRanLiu3119** [comment]
> > 好的，后面版本加，我没用到还以为没啥用呢
> 
> 能添加复制播放链接的按钮吗

啊我忘了,我找地方加下
