### ISSUE TITLE
線路、解析、源不能自動切換，這個功能是否可以開啟？

### ISSUE THREAD

**Issue by slasjh** [XiaoRanLiu3119/TVBoxOS-Mobile#68]
還有一個bug，播放一個電影，切換到後台，再切換回來，畫面是黑的，只有聲音和進度條

**Comment by slasjh** [comment]
必須要重新刷新或者重新打開

**Comment by XiaoRanLiu3119** [comment]
是开了后台播放出现的情况吗

**Comment by slasjh** [comment]
切換程序，後出現的。 v1.0.4   1.0.5   1.0.7。正常播放沒有，使用最小窗和全屏也不會，

**Comment by XiaoRanLiu3119** [comment]
抱歉没太听懂.我这边如何退后台再切换都没有复现,请描述更详细些我好复现以下,有录屏或截图什么的最好

**Comment by slasjh** [comment]
那可能是小米手機和app兼容性問題
![Uploading 1.jpg…]()

**Comment by slasjh** [comment]
![1](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/127065284/d3d14353-1f4d-47c9-af84-908f07b450b5)
![2](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/127065284/80ccf727-65db-47ac-ae66-66870a716ccd)

![3](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/127065284/8868f730-76b0-4003-b5ac-9d2d2bf05caf)

**Comment by XiaoRanLiu3119** [comment]
看到了,不应该呀.我好多小米的机器,你的型号是?麻烦再发我下你用的源,虽然和源应该没关系,我都测试下

**Comment by slasjh** [comment]
紅米K40S,試了很多源，都是這樣 。試了1.0.7沒有這個問題
https://gitee.com/bestpvp/tm/raw/master/source/nightly/main.json

**Comment by XiaoRanLiu3119** [comment]
好新版没问题就用新版吧,最近主要就是优化些bug
