### ISSUE TITLE
64位测试版

### ISSUE THREAD

**Issue by luckyfatpig** [XiaoRanLiu3119/TVBoxOS-Mobile#69]
8 gen3 等芯片不再支持32位的app导致无法使用

**Comment by XiaoRanLiu3119** [comment]
缺少quickjs的64位so包。只能升级，还搞不懂qjs，过阶段再研究研究

**Comment by XiaoRanLiu3119** [comment]
征求熟悉quickjs的大佬

**Comment by XiaoRanLiu3119** [comment]
[MBox_v1.0.8_Dev_Arm64_v8a.zip](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/files/13791168/MBox_v1.0.8_Dev_Arm64_v8a.zip)

**Comment by luckyfatpig** [comment]
> 已上传64位测试版, 最好先复制下订阅, 卸载旧版重新安装64位版

已经在用能正常运行

**Comment by 9292922** [comment]
老哥，直播声音有问题，这个好像是播放器的问题，之前一直都是有问题，不管32或者64位。
就是我把直播源放到影视仓或者easybox是直播有声音的，比如CCTV1或者CCTV2，但是来到mbox就没声音了，我看了看连声音准备完成都没回调，不知道是Java出层还是native层有问题，log也没有。

我给你个直播源测试一下：
https://52.lltv8.cn
