### ISSUE TITLE
强烈建议可以增加一个广告过滤的功能！

### ISSUE THREAD

**Issue by ToKingl** [XiaoRanLiu3119/TVBoxOS-Mobile#70]
如题，现在好多接口都有广告，所以希望tvbox-mobile可以增加这么一个广告过滤的功能！！！

**Comment by XiaoRanLiu3119** [comment]
不懂啊规则不是订阅添加的么,可以试试tk版的能否去除你说的广告,可以的话我尝试添加

**Comment by ToKingl** [comment]
可以去除

**Comment by ToKingl** [comment]
> 不懂啊规则不是订阅添加的么,可以试试tk版的能否去除你说的广告,可以的话我尝试添加

可以去除

**Comment by lzk23559** [comment]
> 不懂啊规则不是订阅添加的么,可以试试tk版的能否去除你说的广告,可以的话我尝试添加

搞蜂蜜影视那种通过配置设置过滤m3u8视频广告规则的，不要用tk仓的那种。

**Comment by XiaoRanLiu3119** [comment]
> > 不懂啊规则不是订阅添加的么,可以试试tk版的能否去除你说的广告,可以的话我尝试添加
> 
> 可以去除

好,过段时间我研究下,方便的话告诉我源、站点、片子、广告显示的分钟数,后续好测试

**Comment by XiaoRanLiu3119** [comment]
> > 不懂啊规则不是订阅添加的么,可以试试tk版的能否去除你说的广告,可以的话我尝试添加
> 
> 搞蜂蜜影视那种通过配置设置过滤m3u8视频广告规则的，不要用tk仓的那种。

tk仓代码相似成本低,蜂蜜的不一定能搞懂,后续有时间再研究

**Comment by ToKingl** [comment]
> > > 不懂啊规则不是订阅添加的么,可以试试tk版的能否去除你说的广告,可以的话我尝试添加
> > 
> > 
> > 搞蜂蜜影视那种通过配置设置过滤m3u8视频广告规则的，不要用tk仓的那种。
> 
> tk仓代码相似成本低,蜂蜜的不一定能搞懂,后续有时间再研究

tk仓有这个广告过滤的功能，源分别有Aoki和环宇轩网络源
![Screenshot_2023-12-30-17-57-54-068_com github tvbox osc tk](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/146187689/42580285-eb94-4961-a628-a1efe926d31d)

Aoki源：
https://aoki.fun/spider.json
环宇轩网络源：
http://www.891218.xyz/免费接口/环宇轩网络/

**Comment by XiaoRanLiu3119** [comment]
不好意思表述有误,比如你说的Aoki源,看哪个站点的哪个视频的第几分钟有广告

**Comment by XiaoRanLiu3119** [comment]
下版本发,同tk版
