### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by zhuziwuming** [XiaoRanLiu3119/TVBoxOS-Mobile#71]
你好，目前发现小问题:
1.本地视频播放录屏视频，方向不对。
2.播放界面设置播放器，代码不能响应长按?字幕可以响应长按
3.能不能修改一下包名称，跟俊版的TV版本冲突

**Comment by XiaoRanLiu3119** [comment]
1换了几个型号的小米手机测试正常
2同上,如是ijk不响应长按倍速,尝试切换exo
3不考虑,俊版更新慢,可用MT管理器的apk共存功能修改俊版包名
