### ISSUE TITLE
添加订阅链接时

### ISSUE THREAD

**Issue by jllyzjs** [XiaoRanLiu3119/TVBoxOS-Mobile#72]
添加订阅链接后，自动存在最下面排列，还要翻到最下面，点击才能使用新添加的订阅。
建议优化一下
添加好订阅，点击"添加"后，直接加载新添加的订阅，在首页自动加载好，节省下翻寻找的步骤。

**Comment by XiaoRanLiu3119** [comment]
合理,我添加个'使用此订阅'选项
