### ISSUE TITLE
字幕有问题

### ISSUE THREAD

**Issue by q7954** [XiaoRanLiu3119/TVBoxOS-Mobile#74]
用的香雅情的jar阿里云盘原画观看字幕显示问题，存到阿里云盘打开看正常
![Screenshot_2024-01-01-07-25-10-748_com github tvbox osc](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/107266885/d374a55e-147a-4008-b52d-320d2b6dba02)

**Comment by XiaoRanLiu3119** [comment]
好的,下版本一起发
