### ISSUE TITLE
部分频道EXO播放直播没声音

### ISSUE THREAD

**Issue by 9292922** [XiaoRanLiu3119/TVBoxOS-Mobile#75]
老哥，直播声音有问题，这个好像是播放器的问题，之前一直都是有问题，不管32或者64位。
就是我把直播源放到影视仓或者easybox是直播有声音的，比如CCTV1或者CCTV2，但是来到mbox就没声音了，我看了看连声音准备完成都没回调，不知道是Java出层还是native层有问题，log也没有。

我给你个直播源测试一下：
https://52.lltv8.cn

**Comment by XiaoRanLiu3119** [comment]
测了下切换ijk正常,那两个app应该都升级且优化过exo播放,我基本不用直播,我的思路是先升级exo,再看看[tk版](https://github.com/takagen99/Box)有什么修复,不过要往后放放

**Comment by 9292922** [comment]
是的，ijk可以，我先测试和修复一下，迟点给您反馈

**Comment by XiaoRanLiu3119** [comment]
不必客气,一起学习

**Comment by HuShanquan3** [comment]
是的，不只是直播，本地多音轨MKV有些也没有声音

**Comment by XiaoRanLiu3119** [comment]
> 是的，不只是直播，本地多音轨MKV有些也没有声音

噢!不知q版是否有这问题,我有时间研究下

**Comment by XiaoRanLiu3119** [comment]
直播源失效了,再有exo没声音的源麻烦发下

**Comment by HuShanquan3** [comment]
https://gitee.com/misrhu/no/blob/master/guide_video.mp4 (gitee存储的视频要下载，不能在线播放)
这个视频用exoplayer开头10s会卡住，好像是自动跳过了静音部分，又好像是exoplayer的bug，使用ijkplayer就是正常的。

**Comment by XiaoRanLiu3119** [comment]
> https://gitee.com/misrhu/no/blob/master/guide_video.mp4 (gitee存储的视频要下载，不能在线播放) 这个视频用exoplayer开头10s会卡住，好像是自动跳过了静音部分，又好像是exoplayer的bug，使用ijkplayer就是正常的。

感谢我看看

**Comment by HuShanquan3** [comment]
> > https://gitee.com/misrhu/no/blob/master/guide_video.mp4 (gitee存储的视频要下载，不能在线播放) 这个视频用exoplayer开头10s会卡住，好像是自动跳过了静音部分，又好像是exoplayer的bug，使用ijkplayer就是正常的。
> 
> 感谢我看看

上面这个视频我自己解决了，是exoplayer参数设置问题，那个视频有点特殊。

**Comment by XiaoRanLiu3119** [comment]
exo加了音频解码,应该没问题了,有线路可测试下
