### ISSUE TITLE
希望优化一下启动白屏

### ISSUE THREAD

**Issue by fxxf1111** [XiaoRanLiu3119/TVBoxOS-Mobile#76]
![Screenshot_2024-01-02-14-55-43-61](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/48472903/bb34e5aa-31a9-42fa-b971-a4091c4eab3a)

系统: Android11  colorOS

**Comment by XiaoRanLiu3119** [comment]
加过一次启动页,我找的太丑了,我再找找加上

**Comment by XiaoRanLiu3119** [comment]
nono做了就做成和正常app一样，下次发版一起发
