### ISSUE TITLE
部分有问题js源直接闪退

### ISSUE THREAD

**Issue by HuShanquan3** [XiaoRanLiu3119/TVBoxOS-Mobile#79]
更换quick之后，js源如果异常，不会提示报错地方，直接闪退，我把相关调用函数的异常抛出都打开了也没有捕获到异常，之前的版本如果js有错，直接会打印出错堆栈，现在直接闪退，没任何信息。我主要是想调试一些js解析源，大佬有什么方法吗

**Comment by XiaoRanLiu3119** [comment]
如果放到线上了或者有本地包啥的我可以跑下看看,或者你调试用tk版试试

**Comment by HuShanquan3** [comment]
这个js是解析源有点问题，解决了，大佬什么时候添加py解析适配呢

**Comment by XiaoRanLiu3119** [comment]
不集成在本项目里,用置顶issue那个仓库的action打包py版本
![image](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/62411322/23c3876f-5df3-42b1-8a31-9b035cbb8735)
