### ISSUE TITLE
0.6版本订阅管理有问题，更新订阅失败，我还是回退到0.4了

### ISSUE THREAD

**Issue by c7877** [XiaoRanLiu3119/TVBoxOS-Mobile#8]

**Comment by XiaoRanLiu3119** [comment]
同一个订阅和首页数据源0.4提示成功吗?
订阅地址和提示失败的首页数据源发我我试试

**Comment by c7877** [comment]
我的是本地包，香佬的

**Comment by c7877** [comment]
![Uploading Screenshot_2023-09-12-22-49-31-589_com.github.tvbox.osc.jpg…]()

**Comment by XiaoRanLiu3119** [comment]
俩图好像都挂了，不过你说本地包，我这也试出来了，谢谢，这两天没用，明个我看看

**Comment by c7877** [comment]
而且就算你出现订阅失败或者如图一串英文字母加本机ip地址之后退app重进会显示订阅成功

**Comment by c7877** [comment]
今天你仓库更新的是在线更新吗？

**Comment by c7877** [comment]
0.6版本好像是不能在线切换线路啊😂，而且我发现香佬的本地包挂了几个我认为能持久的首页源，我在影视上也测了下确实挂了😓

**Comment by c7877** [comment]
0.6在线切换线路会出现失败或另一个提醒，只能退出app重进就好了

**Comment by XiaoRanLiu3119** [comment]
是的，打算和蜂蜜大佬一样建个发版的仓库，把在线更新加上。
在线切换订阅可以的，我最近一直在用0.6，不过是远程多仓的订阅，来回切换没问题呢

**Comment by XiaoRanLiu3119** [comment]
应该是本地包的事，明个看看咋回事

**Comment by XiaoRanLiu3119** [comment]
https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/62411322/f52bd0c5-1082-40d9-aea9-50d078dd7e6d

修好啦，做完升级一起打包
