### ISSUE TITLE
希望兼容hipy道长新开项目。

### ISSUE THREAD

**Issue by q7954** [XiaoRanLiu3119/TVBoxOS-Mobile#84]
https://gitee.com/foxnick/drpyboxd这就是爱佬版，基本道长有啥新货爱佬先更，现在开源了后期不知道会不会隐藏！
https://github.com/hjdhnx/dr_py
https://github.com/hjdhnx/fastapi_vue

**Comment by XiaoRanLiu3119** [comment]
新技术啥的还是影视比较稳,我后面有空再学习学习
