### ISSUE TITLE
编译的时候提示错误，这是什么原因啊

### ISSUE THREAD

**Issue by xiaren2** [XiaoRanLiu3119/TVBoxOS-Mobile#85]
What went wrong:
Execution failed for task ':player:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/home/runner/.gradle/caches/transforms-2/files-2.1/6072fa5c7fe7e1d7d56a15631e8a31c1/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by XiaoRanLiu3119** [comment]
百度下

**Comment by XiaoRanLiu3119** [comment]
如果是github action打包报的这个错,现在可以了,再试下
