### ISSUE TITLE
播放断流问题还是存在

### ISSUE THREAD

**Issue by qq5855144** [XiaoRanLiu3119/TVBoxOS-Mobile#87]
切换播放器时影片又重头开始播放，还可以优化一下。 同一个影片用其它壳子播放不会出错

**Comment by XiaoRanLiu3119** [comment]
目前没遇见呢,源、站点以及视频可以发我我看看

**Comment by qq5855144** [comment]
南瓜APP  豆包县令

**Comment by XiaoRanLiu3119** [comment]
我测试会闪一下开头,再回到进度,不会重播,exo切ijk明显,影响后面不大的话有时间看看如何优化.

https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/62411322/5e6b0c4e-f9a3-4352-8e82-e2946dead40d

**Comment by qq5855144** [comment]
感谢你的付出
