### ISSUE TITLE
能删除不必要的权限索取请求么？

### ISSUE THREAD

**Issue by jak0099** [XiaoRanLiu3119/TVBoxOS-Mobile#9]
大神，能清除不必要的权限请求，仅保留文件读写权限么？自行在AndroidManifest.xml中删除多余权限行不通，会报错说安装包无效或不完整或与系统不兼容，原Q版tvbox在AndroidManifest.xml中删除多余权限不会报错的哦
![Screenshot_20230912_004050_com android packageinstaller](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/90884864/7b4ddae2-4459-4494-ba25-fd91a08312fe)

**Comment by XiaoRanLiu3119** [comment]
删除清单文件的权限,不会装不上啊,安装前看看是否已经安装相同包名/签名的tvbox了,还有打release包安装试试,debug包无法直接安装

**Comment by jak0099** [comment]
都是基于你的release包修改的，0.02版本是直接在NP管理器上删清单权限然后签名就可以安装的了，最近几版不行，按照你给的思路，NP上换了包名和签名文件都是报上图的错误；我用Apktool M测试删清单权限签名也安装不了，然后测试反编译解包，然后删清单权限，再打包，可以正常安装，最后我换MT测试了一下，直接删清单权限签名，可以正常安装apk,综上不知道是不是原包有bug?Q版及其他box系列版本随便删清单多余权限都不会报错的，希望这情况能给你提供到帮助

**Comment by XiaoRanLiu3119** [comment]
https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/62411322/21af1ef6-fa60-4692-af82-8ae6d22d6db9

是这意思么？我可以呀，是不是删多了

**Comment by XiaoRanLiu3119** [comment]
另外网络状态相关的权限,播放器有用到,定位权限只声明没动态申请,安装权限后续升级会用,故源码不作删除
