### ISSUE TITLE
背景听到视频播放了，画面还是在显示：正在嗅探播放地址

### ISSUE THREAD

**Issue by tiancool** [XiaoRanLiu3119/TVBoxOS-Mobile#91]
![WechatIMG83](https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/20513278/62c10471-e0d4-4323-b959-227104db7149)

**Comment by XiaoRanLiu3119** [comment]
我找到腾云驾雾js的没问题,遇见了再看看
